# Generated by Django 5.1.4 on 2024-12-26 10:07

import app.models
import django.core.validators
import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=100, verbose_name='Mot de passe')),
                ('profile_photo', models.ImageField(blank=True, help_text='Format accepté : JPG, PNG. Taille max : 2MB', null=True, upload_to=app.models.profile_photo_path, verbose_name='Photo de profil')),
                ('applicant_count', models.IntegerField(default=1, verbose_name='Nombre de demandeurs')),
                ('category', models.CharField(choices=[('n', 'Normal'), ('pm', 'Premium'), ('pt', 'Prime Time')], max_length=2, verbose_name='Catégorie')),
                ('location', models.CharField(choices=[('rabat', 'Rabat'), ('casa', 'Casablanca'), ('tanger', 'Tanger'), ('tetouan', 'Tétouan'), ('nador', 'Nador')], max_length=10, verbose_name='Localisation')),
                ('visa', models.CharField(choices=[('sch', 'Schengen'), ('std', 'Étudiant'), ('famr', 'Regroupement familial'), ('nat', 'National'), ('work', 'Travail'), ('c1', 'Catégorie 1'), ('c2', 'Catégorie 2'), ('c3', 'Catégorie 3')], max_length=4, verbose_name='Type de visa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Candidat',
                'verbose_name_plural': 'Candidats',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'organisation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='CarteBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_titulaire', models.CharField(help_text="Nom tel qu'il apparaît sur la carte", max_length=100, verbose_name='Nom du titulaire')),
                ('numero', encrypted_model_fields.fields.EncryptedCharField(help_text='16 chiffres sans espaces', validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Numéro de carte')),
                ('date_expiration', models.DateField(help_text='Format: MM/YYYY', verbose_name="Date d'expiration")),
                ('cvv', encrypted_model_fields.fields.EncryptedCharField(help_text='3 ou 4 chiffres au dos de la carte', validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Code CVV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajoutée le')),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_bancaire', to='app.candidat', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Carte bancaire',
                'verbose_name_plural': 'Cartes bancaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidat',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.organisation', verbose_name='Organisation'),
        ),
        migrations.CreateModel(
            name='OrganisationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('staff', 'Staff'), ('viewer', 'Lecteur')], default='viewer', max_length=10)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organisation')},
            },
        ),
    ]
