# Generated by Django 5.1.4 on 2024-12-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organisation')),
                ('permissions', models.ManyToManyField(to='auth.permission')),
            ],
            options={
                'verbose_name': "Rôle d'organisation",
                'verbose_name_plural': "Rôles d'organisation",
                'unique_together': {('name', 'organisation')},
            },
        ),
    ]
