# Generated by Django 5.1.4 on 2024-12-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_organisationrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine exécution')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('attempts', models.IntegerField(default=0, verbose_name='Tentatives')),
                ('success', models.BooleanField(default=False, verbose_name='Succès')),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scraping_task', to='app.candidat', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Tâche de scraping',
                'verbose_name_plural': 'Tâches de scraping',
            },
        ),
    ]
