# Generated by Django 5.1.4 on 2024-12-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_scrapingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du rendez-vous'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='appointment_details',
            field=models.TextField(blank=True, verbose_name='Détails du rendez-vous'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('appointment_set', 'Rendez-vous pris'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut du rendez-vous'),
        ),
    ]
