# Generated by Django 5.1.4 on 2024-12-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_candidat_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'verbose_name': 'Demandeur de visa', 'verbose_name_plural': 'Demandeurs de visa'},
        ),
        migrations.AlterModelOptions(
            name='cartebancaire',
            options={'ordering': ['-created_at'], 'verbose_name': 'Moyen de paiement', 'verbose_name_plural': 'Moyens de paiement'},
        ),
        migrations.AlterModelOptions(
            name='scrapingtask',
            options={'verbose_name': 'Tâche de rendez-vous', 'verbose_name_plural': 'Tâches de rendez-vous'},
        ),
        migrations.AddField(
            model_name='candidat',
            name='country_of_residence',
            field=models.CharField(default='Morocco', max_length=100, verbose_name='Pays de résidence'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='date_of_birth',
            field=models.DateField(default='1990-01-01', verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='first_name',
            field=models.CharField(default='John', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100, verbose_name='Deuxième prénom'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='passport_expiry_date',
            field=models.DateField(default='2024-01-01', verbose_name="Date d'expiration du passeport"),
        ),
        migrations.AddField(
            model_name='candidat',
            name='passport_issue_country',
            field=models.CharField(default='Morocco', max_length=100, verbose_name="Pays d'émission du passeport"),
        ),
        migrations.AddField(
            model_name='candidat',
            name='passport_issue_date',
            field=models.DateField(default='2024-01-01', verbose_name="Date d'émission du passeport"),
        ),
        migrations.AddField(
            model_name='candidat',
            name='passport_issue_place',
            field=models.CharField(default='Rabat', max_length=100, verbose_name="Lieu d'émission du passeport"),
        ),
        migrations.AddField(
            model_name='candidat',
            name='passport_number',
            field=models.CharField(default='1234567890', max_length=20, verbose_name='Numéro de passeport'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='passport_type',
            field=models.CharField(choices=[('ordinary', 'Ordinaire'), ('diplomatic', 'Diplomatique'), ('service', 'Service'), ('other', 'Autre')], default='ordinary', max_length=20, verbose_name='Type de passeport'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='phone_country_code',
            field=models.CharField(default='+212', max_length=5, verbose_name='Code pays'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='phone_number',
            field=models.CharField(default='0606060606', max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='surname',
            field=models.CharField(default='Doe', max_length=100, verbose_name='Nom de famille'),
        ),
    ]
