# Generated by Django 5.1.4 on 2024-12-27 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_candidat_options_alter_cartebancaire_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='phone_country_code',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='phone_number',
            field=models.CharField(default='+212612345678', help_text='Format: +212612345678', max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit commencer par +212 et être suivi de 9 chiffres. Ex: +212612345678', regex='^\\+212[5-7][0-9]{8}$')], verbose_name='Numéro de téléphone'),
        ),
    ]
