# Generated by Django 5.1.4 on 2024-12-27 10:36

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_candidat_phone_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='country_of_residence',
            field=django_countries.fields.CountryField(default='MA', max_length=2, verbose_name='Pays de résidence'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='passport_issue_country',
            field=django_countries.fields.CountryField(default='MA', max_length=2, verbose_name="Pays d'émission du passeport"),
        ),
    ]
