# Generated by Django 5.1.4 on 2024-12-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_candidat_country_of_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deuxième prénom'),
        ),
    ]
