# Generated by Django 5.1.4 on 2024-12-27 11:08

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_candidat_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='proxy_host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse du proxy'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='proxy_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Mot de passe proxy'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='proxy_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='Port du proxy'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='proxy_username',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name="Nom d'utilisateur proxy"),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('appointment_set', 'Rendez-vous pris'), ('failed', '��chec')], default='pending', max_length=20, verbose_name='Statut du rendez-vous'),
        ),
    ]
