# Generated by Django 5.1.4 on 2024-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_organisation_proxy_host_organisation_proxy_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('appointment_set', 'Rendez-vous pris'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut du rendez-vous'),
        ),
    ]
