# Generated by Django 5.1.4 on 2024-12-27 15:31

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_candidat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='proxy_host',
            field=models.CharField(blank=True, help_text='Utilisez le format complet dans le champ Configuration du proxy', max_length=255, null=True, verbose_name='Adresse du proxy (non utilisé)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='proxy_password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Utilisez le format complet dans le champ Configuration du proxy', null=True, verbose_name='Mot de passe proxy (non utilisé)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='proxy_port',
            field=models.IntegerField(blank=True, help_text='Utilisez le format complet dans le champ Configuration du proxy', null=True, verbose_name='Port du proxy (non utilisé)'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='proxy_username',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Format: username:password@host:port', null=True, verbose_name='Configuration du proxy'),
        ),
    ]
