# Generated by Django 5.1.4 on 2024-12-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_organisation_proxy_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='proxy_username',
            new_name='proxy',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='proxy_host',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='proxy_password',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='proxy_port',
        ),
    ]
