# Generated by Django 5.1.4 on 2024-12-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_proxy_username_organisation_proxy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='applicant_count',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='surname',
        ),
        migrations.AlterField(
            model_name='candidat',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='last_name',
            field=models.CharField(default='Anzar', max_length=100, verbose_name='Nom de famille'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidat',
            name='visa',
            field=models.CharField(choices=[('sch', 'Schengen'), ('std', 'Étudiant'), ('famr', 'Regroupement familial'), ('nat', 'National'), ('work', 'Travail')], max_length=4, verbose_name='Type de visa'),
        ),
    ]
