# Generated by Django 5.1.4 on 2024-12-27 18:18

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_candidat_applicant_count_remove_candidat_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartebancaire',
            options={'verbose_name': 'Carte bancaire', 'verbose_name_plural': 'Cartes bancaires'},
        ),
        migrations.RemoveField(
            model_name='cartebancaire',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='cartebancaire',
            name='candidat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.candidat', verbose_name='Candidat'),
        ),
        migrations.AlterField(
            model_name='cartebancaire',
            name='cvv',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Code CVV'),
        ),
        migrations.AlterField(
            model_name='cartebancaire',
            name='date_expiration',
            field=models.DateField(verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='cartebancaire',
            name='nom_titulaire',
            field=models.CharField(max_length=100, verbose_name='Nom du titulaire'),
        ),
        migrations.AlterField(
            model_name='cartebancaire',
            name='numero',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='Numéro de carte'),
        ),
    ]
