# Generated by Django 5.1.4 on 2024-12-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_cartebancaire_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='date_expiration',
            field=models.DateField(help_text='Format: AAAA-MM-JJ', verbose_name="Date d'expiration"),
        ),
    ]
