# Generated by Django 5.1.4 on 2024-12-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cartebancaire_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='passport_issue_place',
            field=models.CharField(default='Morocco', max_length=100, verbose_name="Lieu d'émission du passeport"),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='passport_type',
            field=models.CharField(choices=[('ordinary', 'Ordinary Passport'), ('collective', 'Collective Passport'), ('diplomatic', 'Diplomatic Passport'), ('apatridas', 'D. Viaje Apatridas C. New York'), ('government', 'Government official on duty'), ('national', 'National laissez-passer'), ('official', 'Official Passport'), ('foreigners', 'Passport of foreigners'), ('protection', 'Protection passport'), ('refugee', 'Refugee Travel Document (Geneva Convention)'), ('seaman', 'Seaman book'), ('un', 'UN laissez-passer')], default='ordinary', max_length=20, verbose_name='Type de passeport'),
        ),
    ]
