# Generated by Django 5.1.4 on 2024-12-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_candidat_passport_issue_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='date_expiration',
            field=models.CharField(help_text='Format: MM/AA (ex: 12/25)', max_length=5, verbose_name="Date d'expiration"),
        ),
    ]
