# Generated by Django 5.1.4 on 2024-12-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_cartebancaire_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='date_expiration',
            field=models.DateField(help_text='Format: AAAA-MM-JJ', verbose_name="Date d'expiration"),
        ),
    ]
