# Generated by Django 5.1.4 on 2024-12-30 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_cartebancaire_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='passport_number',
            field=models.CharField(help_text='Format requis : 2 lettres majuscules suivies de 7 chiffres (ex: AB1234567)', max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_passport_number', message='Le numéro de passeport doit contenir 2 lettres majuscules suivies de 7 chiffres (ex: AB1234567)', regex='^[A-Z]{2}\\d{7}$')]),
        ),
    ]
