# Generated by Django 5.1.4 on 2024-12-30 10:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_candidat_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_of_birth',
            field=models.DateField(help_text="La date de naissance ne peut pas être aujourd'hui ni une date future", validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 12, 30), message="La date de naissance ne peut pas être aujourd'hui ni une date future")], verbose_name='Date de naissance'),
        ),
    ]
