# Generated by Django 5.1.4 on 2024-12-30 13:57

import app.models
import app.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_candidat_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organisation', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='passport_expiry_date',
            field=models.DateField(verbose_name="Date d'expiration du passeport"),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='passport_issue_date',
            field=models.DateField(verbose_name="Date d'émission du passeport"),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='passport_issue_place',
            field=models.CharField(max_length=100, verbose_name="Lieu d'émission du passeport"),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='passport_number',
            field=models.CharField(help_text='Format requis : 2 lettres majuscules suivies de 7 chiffres (ex: AB1234567)', max_length=9, validators=[django.core.validators.RegexValidator(message='Le numéro de passeport doit contenir 2 lettres majuscules suivies de 7 chiffres (ex: AB1234567)', regex='^[A-Z]{2}\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='phone_number',
            field=models.CharField(help_text='Format: +212612345678', max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit commencer par +212 et être suivi de 9 chiffres. Ex: +212612345678', regex='^\\+212[5-7][0-9]{8}$')], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Format accepté : JPG, PNG. Taille max : 2MB', null=True, upload_to=app.models.profile_photo_path, validators=[app.utils.validators.validate_photo_size, app.utils.validators.validate_photo_extension], verbose_name='Photo de profil'),
        ),
    ]
