# Generated by Django 5.1.4 on 2024-12-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_candidat_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
    ]
