# Generated by Django 5.1.4 on 2024-12-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_candidat_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code OTP'),
        ),
    ]
