# Generated by Django 5.1.4 on 2024-12-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_scrapingtask_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='temp_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mot de passe temporaire'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('waiting_otp', 'En attente OTP'), ('appointment_set', 'Rendez-vous pris'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut du rendez-vous'),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('waiting_otp', 'En attente OTP'), ('waiting_password', 'En attente mot de passe'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
