# Generated by Django 5.1.4 on 2024-12-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_scrapingtask_temp_password_alter_candidat_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('waiting_otp', 'En attente OTP'), ('appointment_set', 'Rendez-vous pris'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
