# Generated by Django 5.1.4 on 2024-12-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_candidat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('waiting_otp', 'En attente OTP'), ('waiting_password', 'En attente mot de passe'), ('appointment_set', 'Rendez-vous pris'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
