# Generated by Django 5.1.4 on 2024-12-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_candidat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='new_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nouveau mot de passe'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('waiting_otp', 'En attente OTP'), ('waiting_password', 'En attente mot de passe'), ('appointment_set', 'Inscription BLS réussie'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
