# Generated by Django 5.1.4 on 2025-01-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_scrapingtask_new_password_alter_candidat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='checkpoint',
            field=models.CharField(blank=True, help_text='Utilisé uniquement en mode développement', max_length=50, null=True, verbose_name='Point de reprise'),
        ),
    ]
