# Generated by Django 5.1.4 on 2025-01-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_scrapingtask_checkpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingtask',
            name='checkpoint',
        ),
    ]
