# Generated by Django 5.1.4 on 2025-01-02 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_scrapingtask_checkpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='date_expiration',
            field=models.CharField(help_text='Format: MM/YY', max_length=5, validators=[django.core.validators.RegexValidator(message="La date d'expiration doit être au format MM/YY (ex: 05/25)", regex='^(0[1-9]|1[0-2])/([0-9]{2})$')], verbose_name="Date d'expiration"),
        ),
    ]
