# Generated by Django 5.1.4 on 2025-01-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_cartebancaire_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartebancaire',
            name='date_expiration',
            field=models.DateField(help_text='Format: MM/YY (ex: 05/25)', verbose_name="Date d'expiration"),
        ),
    ]
