# Generated by Django 5.1.4 on 2025-01-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_cartebancaire_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('waiting_otp', 'En attente OTP'), ('waiting_password', 'En attente mot de passe'), ('inscription_set', 'Inscription BLS réussie'), ('failed', 'Échec'), ('connected', 'Connecté')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
