# Generated by Django 5.1.4 on 2025-01-04 22:56

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_candidat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='country_of_birth',
            field=django_countries.fields.CountryField(default='MA', max_length=2, verbose_name='Pays de naissance'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='current_nationality',
            field=django_countries.fields.CountryField(default='MA', max_length=2, verbose_name='Nationalité actuelle'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], default='single', max_length=10, verbose_name='État civil'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='nationality_at_birth',
            field=django_countries.fields.CountryField(blank=True, default='MA', max_length=2, null=True, verbose_name='Nationalité à la naissance'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='surname_at_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de naissance'),
        ),
    ]
