# Generated by Django 5.1.4 on 2025-01-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_candidat_country_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='travel_date',
            field=models.DateField(blank=True, help_text='Date prévue du voyage', null=True, verbose_name='Date de voyage'),
        ),
    ]
