# Generated by Django 5.1.4 on 2025-01-04 23:11

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_candidat_travel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='intended_stay_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Durée en jours', null=True, verbose_name='Durée prévue du séjour'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='member_state_destination',
            field=django_countries.fields.CountryField(default='ES', max_length=2, verbose_name='Pays de destination principal'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='member_state_first_entry',
            field=django_countries.fields.CountryField(blank=True, default='ES', max_length=2, null=True, verbose_name='Pays de première entrée'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='member_state_second_destination',
            field=django_countries.fields.CountryField(blank=True, default='ES', max_length=2, null=True, verbose_name='Pays de destination secondaire'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='number_of_entries',
            field=models.CharField(choices=[('1', 'Single Entry'), ('2', 'Double Entry'), ('M', 'Multiple Entry')], default='1', max_length=1, verbose_name="Nombre d'entrées demandées"),
        ),
        migrations.AddField(
            model_name='candidat',
            name='purpose_of_journey',
            field=models.CharField(choices=[('tourism', 'Tourism'), ('business', 'Business'), ('study', 'Study'), ('family', 'Family Visit'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('official', 'Official Visit'), ('medical', 'Medical'), ('other', 'Other')], default='tourism', help_text='Objectif principal du voyage', max_length=20, verbose_name='But du voyage'),
        ),
    ]
