# Generated by Django 5.1.4 on 2025-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_candidat_intended_stay_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='location',
            field=models.CharField(choices=[('rabat', 'Rabat'), ('casa', 'Casablanca'), ('tanger', 'Tanger'), ('tetouan', 'Tétouan'), ('nador', 'Nador'), ('agadir', 'Agadir')], max_length=10, verbose_name='Localisation'),
        ),
    ]
