# Generated by Django 5.1.4 on 2025-01-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_candidat_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='visa',
            field=models.CharField(choices=[('sch', 'Schengen Visa'), ('std', 'Étudiant'), ('famr', 'Regroupement familial'), ('nat', 'National Visa'), ('work', 'Travail')], max_length=4, verbose_name='Type de visa'),
        ),
    ]
