# Generated by Django 5.1.4 on 2025-01-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_candidat_gender_alter_candidat_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='single', max_length=10, verbose_name='État civil'),
        ),
    ]
