# Generated by Django 5.1.4 on 2025-01-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_candidat_passport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='passport_type',
            field=models.CharField(choices=[('Ordinary Passport', 'Ordinary Passport'), ('Collective Passport', 'Collective Passport'), ('Diplomatic Passport', 'Diplomatic Passport'), ('D. Viaje Apatridas C. New York', 'D. Viaje Apatridas C. New York'), ('Government official on duty', 'Government official on duty'), ('National laissez-passer', 'National laissez-passer'), ('Official Passport', 'Official Passport'), ('Passport of foreigners', 'Passport of foreigners'), ('Protection passport', 'Protection passport'), ('Refugee Travel Document (Geneva Convention)', 'Refugee Travel Document (Geneva Convention)'), ('Seaman book', 'Seaman book'), ('UN laissez-passer', 'UN laissez-passer')], default='Ordinary Passport', max_length=120, verbose_name='Type de passeport'),
        ),
    ]
