# Generated by Django 5.1.4 on 2025-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_candidat_passport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='passport_type',
            field=models.CharField(choices=[('ordinary', 'Ordinary Passport'), ('collective', 'Collective Passport'), ('diplomatic', 'Diplomatic Passport'), ('apatridas', 'D. Viaje Apatridas C. New York'), ('government', 'Government official on duty'), ('national', 'National laissez-passer'), ('official', 'Official Passport'), ('foreigners', 'Passport of foreigners'), ('protection', 'Protection passport'), ('refugee', 'Refugee Travel Document (Geneva Convention)'), ('seaman', 'Seaman book'), ('un', 'UN laissez-passer')], default='ordinary', max_length=120, verbose_name='Type de passeport'),
        ),
    ]
