# Generated by Django 5.1.4 on 2025-01-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_candidat_passport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='purpose_of_journey',
            field=models.CharField(choices=[('tourism', 'Tourism'), ('airport', 'Airport Transit'), ('business', 'Business'), ('study', 'Study'), ('family', 'Family Visit'), ('cultural', 'Cultural reasons'), ('sports', 'Sports'), ('official', 'Official visit'), ('medical', 'Medical reasons'), ('other', 'Others'), ('transit', 'Transit'), ('visiting', 'Visiting family')], default='tourism', help_text='Objectif principal du voyage', max_length=20, verbose_name='But du voyage'),
        ),
    ]
