# Generated by Django 5.1.4 on 2025-01-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_candidat_purpose_of_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='purpose_of_journey',
            field=models.CharField(choices=[('Tourism', 'Tourism'), ('Airport Transit', 'Airport Transit'), ('Business', 'Business'), ('Study', 'Study'), ('Cultural reasons', 'Cultural reasons'), ('Sports', 'Sports'), ('Official visit', 'Official visit'), ('Medical reasons', 'Medical reasons'), ('Transit', 'Transit'), ('Visiting family', 'Visiting family'), ('Others', 'Others')], default='Tourism', help_text='Objectif principal du voyage', max_length=50, verbose_name='But du voyage'),
        ),
    ]
