# Generated by Django 5.1.4 on 2025-01-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_candidat_purpose_of_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='member_state_destination',
            field=models.CharField(choices=[('Spain', 'Spain'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('Portugal', 'Portugal'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('Luxembourg', 'Luxembourg'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Denmark', 'Denmark'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Iceland', 'Iceland'), ('Greece', 'Greece'), ('Czech Republic', 'Czech Republic'), ('Hungary', 'Hungary'), ('Poland', 'Poland'), ('Estonia', 'Estonia'), ('Latvia', 'Latvia'), ('Lithuania', 'Lithuania'), ('Malta', 'Malta'), ('Slovenia', 'Slovenia'), ('Slovakia', 'Slovakia')], default='Spain', max_length=50, verbose_name='Pays de destination principal'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='member_state_first_entry',
            field=models.CharField(blank=True, choices=[('Spain', 'Spain'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('Portugal', 'Portugal'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('Luxembourg', 'Luxembourg'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Denmark', 'Denmark'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Iceland', 'Iceland'), ('Greece', 'Greece'), ('Czech Republic', 'Czech Republic'), ('Hungary', 'Hungary'), ('Poland', 'Poland'), ('Estonia', 'Estonia'), ('Latvia', 'Latvia'), ('Lithuania', 'Lithuania'), ('Malta', 'Malta'), ('Slovenia', 'Slovenia'), ('Slovakia', 'Slovakia')], default='Spain', max_length=50, null=True, verbose_name='Pays de première entrée'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='member_state_second_destination',
            field=models.CharField(blank=True, choices=[('Spain', 'Spain'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('Portugal', 'Portugal'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('Luxembourg', 'Luxembourg'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Denmark', 'Denmark'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Iceland', 'Iceland'), ('Greece', 'Greece'), ('Czech Republic', 'Czech Republic'), ('Hungary', 'Hungary'), ('Poland', 'Poland'), ('Estonia', 'Estonia'), ('Latvia', 'Latvia'), ('Lithuania', 'Lithuania'), ('Malta', 'Malta'), ('Slovenia', 'Slovenia'), ('Slovakia', 'Slovakia')], default='Spain', max_length=50, null=True, verbose_name='Pays de destination secondaire'),
        ),
    ]
