# Generated by Django 5.1.4 on 2025-01-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_candidat_member_state_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='passport_type',
            field=models.CharField(choices=[('Ordinary Passport', 'Ordinary Passport'), ('Collective Passport', 'Collective Passport'), ('Diplomatic Passport', 'Diplomatic Passport'), ('D. Viaje Apatridas C. New York', 'D. Viaje Apatridas C. New York'), ('Government official on duty', '   '), ('National laissez-passer', 'National laissez-passer'), ('Official Passport', 'Official Passport'), ('Passport of foreigners', 'Passport of foreigners'), ('Protection passport', 'Protection passport'), ('Refugee Travel Document (Geneva Convention)', 'Refugee Travel Document (Geneva Convention)'), ('Seaman book', 'Seaman book'), ('UN laissez-passer', 'UN laissez-passer')], default='ordinary', max_length=120, verbose_name='Type de passeport'),
        ),
    ]
