# Generated by Django 5.1.4 on 2025-01-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_candidat_passport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='data_protection_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de confirmation protection des données'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('waiting_otp', 'En attente OTP'), ('waiting_password', 'En attente mot de passe'), ('inscription_set', 'Inscription BLS réussie'), ('failed', 'Échec'), ('connected', 'Connecté'), ('waiting_data_protection', 'En attente URL de protection des données')], default='pending', max_length=50, verbose_name='Statut'),
        ),
    ]
