# Generated by Django 5.1.4 on 2025-01-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_scrapingtask_data_protection_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('waiting_otp', 'En attente OTP'), ('waiting_password', 'En attente mot de passe'), ('inscription_set', 'Inscription BLS réussie'), ('failed', 'Échec'), ('connected', 'Connecté'), ('waiting_data_protection', 'En attente URL de protection des données')], default='pending', max_length=100, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('waiting_otp', 'En attente OTP'), ('waiting_password', 'En attente mot de passe'), ('waiting_data_protection', 'En attente URL de protection des données'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=50, verbose_name='Statut'),
        ),
    ]
