# Generated by Django 5.1.4 on 2025-01-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_alter_candidat_status_alter_scrapingtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='visa',
            field=models.CharField(choices=[('sch', 'Schengen Visa'), ('std', 'Étudiant'), ('famr', 'Regroupement familial'), ('nat', 'National Visa'), ('work', 'Travail'), ('casa1', 'Casa 1'), ('casa2', 'Casa 2'), ('casa3', 'Casa 3')], max_length=100, verbose_name='Type de visa'),
        ),
    ]
