# Generated by Django 5.1.4 on 2025-01-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_candidat_visa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('staff', 'Staff')], default='viewer', max_length=10),
        ),
    ]
