# Generated by Django 5.1.4 on 2025-01-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_organisationuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
    ]
