# Generated by Django 5.1.4 on 2025-01-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_organisationuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='proxy',
            field=models.CharField(blank=True, help_text='Format: username:password@host:port', max_length=255, null=True, verbose_name='Configuration du proxy'),
        ),
    ]
