# Generated by Django 5.1.4 on 2025-01-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_candidat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de traitement'), ('processing', 'En cours de traitement'), ('waiting_otp', 'En attente OTP'), ('waiting_password', 'En attente mot de passe'), ('inscription_set', 'Inscription BLS réussie'), ('failed', 'Échec'), ('connected', 'Connecté'), ('waiting_data_protection', 'En attente URL de protection des données'), ('passport_already_used', ' Erreur - Passeport déjà utilisé '), ('mobile_number_already_used', ' Erreur - Numéro de téléphone déjà utilisé ')], default='pending', max_length=100, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='data_protection_url',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL de confirmation protection des données'),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='new_password',
            field=models.CharField(blank=True, help_text='Nouveau mot de passe BLS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapingtask',
            name='otp',
            field=models.CharField(blank=True, help_text='Code OTP reçu', max_length=10, null=True),
        ),
    ]
