# Generated by Django 5.1.4 on 2025-01-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_candidat_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='visa_sub_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sous-type de visa'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='location',
            field=models.CharField(choices=[('rabat', 'Rabat'), ('casa', 'Casablanca'), ('tanger', 'Tanger'), ('tetouan', 'Tétouan'), ('nador', 'Nador'), ('agadir', 'Agadir')], max_length=100, verbose_name='Localisation'),
        ),
    ]
