# Generated by Django 5.1.4 on 2025-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_candidat_visa_sub_type_alter_candidat_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='visa_sub_type',
        ),
        migrations.AddField(
            model_name='candidat',
            name='visa_subtype',
            field=models.CharField(blank=True, choices=[('casa1', 'Casa 1'), ('casa2', 'Casa 2'), ('casa3', 'Casa 3'), ('nat', 'National Visa')], max_length=100, null=True, verbose_name='Sous-type de visa'),
        ),
    ]
