# Generated by Django 5.1.4 on 2025-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_candidat_visa_sub_type_candidat_visa_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='visa_subtype',
            field=models.CharField(choices=[('casa1', 'Casa 1'), ('casa2', 'Casa 2'), ('casa3', 'Casa 3'), ('nat', 'National Visa')], default='casa1', max_length=100, verbose_name='Sous-type de visa'),
        ),
    ]
