# Generated by Django 5.1.4 on 2025-01-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_alter_candidat_visa_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='category',
            field=models.CharField(choices=[('Normal    ', 'Normal'), ('Premium', 'Premium'), ('Prime Time', 'Prime Time')], max_length=50, verbose_name='Catégorie'),
        ),
    ]
