# Generated by Django 5.1.4 on 2025-01-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_candidat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='category',
            field=models.CharField(choices=[('normal', 'Normal'), ('premium', 'Premium'), ('prime_time', 'Prime Time')], max_length=50, verbose_name='Catégorie'),
        ),
    ]
