# Generated by Django 5.1.4 on 2025-01-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_candidat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='location',
            field=models.CharField(choices=[('rabat', 'Rabat'), ('casa', 'Casablanca'), ('tanger', 'Tanger'), ('tetouan', 'Tetouan'), ('nador', 'Nador'), ('agadir', 'Agadir')], max_length=100, verbose_name='Localisation'),
        ),
    ]
