# Generated by Django 5.1.4 on 2025-01-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_alter_candidat_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='visa_subtype',
            field=models.CharField(choices=[('casa1', 'Casa 1'), ('casa2', 'Casa 2'), ('casa3', 'Casa 3'), ('nat', 'National Visa'), ('sch', 'Schengen Visa'), ('std', 'Étudiant'), ('famr', 'Regroupement familial'), ('work', 'Travail')], default='casa1', max_length=100, verbose_name='Sous-type de visa'),
        ),
    ]
