# Generated by Django 5.1.4 on 2025-01-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_alter_candidat_visa_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookies', models.JSONField(blank=True, null=True, verbose_name='Cookies du navigateur')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='Dernière utilisation')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Session valide')),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='browser_session', to='app.candidat')),
            ],
            options={
                'verbose_name': 'Session navigateur',
                'verbose_name_plural': 'Sessions navigateur',
            },
        ),
    ]
