# Generated by Django 5.1.4 on 2025-01-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_delete_browsersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='location',
            field=models.CharField(choices=[('rabat', 'Rabat'), ('casa', 'Casablanca'), ('tangier', 'Tangier'), ('tetouan', 'Tetouan'), ('nador', 'Nador'), ('agadir', 'Agadir')], max_length=100, verbose_name='Localisation'),
        ),
    ]
